# Generated by Django 5.1.5 on 2025-02-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientworkassignto',
            options={'verbose_name': 'ClinetWorkAssignTo'},
        ),
    ]
