# Generated by Django 5.1.5 on 2025-02-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_alter_clientworkassignto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwork',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
