# Generated by Django 5.1.5 on 2025-02-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientworkassignto',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
