# Generated by Django 5.1.5 on 2025-02-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_clientworkassignto_work_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='clientwork',
            options={'verbose_name': 'Client Work', 'verbose_name_plural': 'Client Works'},
        ),
        migrations.AlterModelOptions(
            name='clientworkassignto',
            options={'verbose_name': 'Client Work Assign To', 'verbose_name_plural': 'Client Work Assign To'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
