# Generated by Django 5.1.5 on 2025-02-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_alter_client_options_alter_clientwork_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientworkassignto',
            name='work_description',
        ),
    ]
