# Generated by Django 5.1.5 on 2025-02-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_remove_clientworkassignto_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwork',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientwork',
            name='proposal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientwork',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='clientwork',
            name='work_started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
