# Generated by Django 5.1.5 on 2025-02-10 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_clientwork_assign_to_alter_clientwork_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwork',
            name='status',
            field=models.CharField(choices=[('in_queue', 'In queue'), ('ongoing', 'Ongoing'), ('waiting_for_approval', 'Waiting for approval'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientwork',
            name='work_started_at',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
