# Generated by Django 5.1.5 on 2025-02-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_alter_clientwork_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwork',
            name='work_started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
