# Generated by Django 5.1.5 on 2025-02-14 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_usercanviewotherteammembertask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCanViewOtherTeamMemberTask',
            new_name='AllowUserToViewOtherTeamMemberTask',
        ),
        migrations.AlterModelOptions(
            name='allowusertoviewotherteammembertask',
            options={'verbose_name': 'Allow user to view other team member task board', 'verbose_name_plural': 'Allow user to view other team member task board'},
        ),
        migrations.AlterModelOptions(
            name='userteamviewpermission',
            options={'verbose_name': 'Allow user to view team dasboard', 'verbose_name_plural': 'Allow user to view team dasboard'},
        ),
    ]
