# Generated by Django 5.1.5 on 2025-02-14 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0016_rename_usercanviewotherteammembertask_allowusertoviewotherteammembertask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCanManageOtherTeamMemberTask',
            new_name='AllowUserToManageOtherTeamMemberTaskBoard',
        ),
    ]
