# Generated by Django 5.1.5 on 2025-02-14 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0017_rename_usercanmanageotherteammembertask_allowusertomanageotherteammembertaskboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllowUserToManageOtherTeamMemberTaskBoard',
            new_name='UserCanManageOtherTeamMemberTask',
        ),
    ]
