# Generated by Django 5.1.5 on 2025-02-14 13:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0018_rename_allowusertomanageotherteammembertaskboard_usercanmanageotherteammembertask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCanManageOtherTeamMemberTask',
            new_name='AllowUserToManageOtherTeamMemberTaskBoard',
        ),
    ]
