# Generated by Django 5.1.5 on 2025-02-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0019_rename_usercanmanageotherteammembertask_allowusertomanageotherteammembertaskboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowusertoviewotherteammembertask',
            options={},
        ),
    ]
